### ISSUE TITLE
Prototype Design for Ordering System

### ISSUE THREAD

**Issue by Greed003** [Greed003/softeng_codename#3]
**Description**
As a customer, I want to be able to easily place an order through a user-friendly interface, so that I can quickly and efficiently purchase products without confusion or delay.
---
**Acceptance Criteria**
- [x] The ordering system prototype includes a clear and intuitive product catalog.
- [x] The checkout process is streamlined and requires minimal steps to complete a purchase.
- [x] Users can view and edit their order summary before finalizing the purchase.

---
**Priority**
High
---
**Estimation**
Story points (1, 2, 3, 5, 8, 13, 21)
---
**Definition of Done**
- All acceptance criteria met.
- Code reviewed and merge.
- Test written and passing.
- Document updated(if possible)

**Comment by leervflores** [comment]
do again mr celestino

**Comment by Greed003** [comment]
https://www.figma.com/design/XcYehX9VWMbt78ESfeBgkC/Untitled?node-id=0-1&t=NpwAArIRqwtzY4OB-1
